---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/items":
    get:
      summary: Retrieves all items
      tags:
      - Items
      responses:
        '200':
          description: items found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    item_type:
                      type: string
                    price:
                      type: number
                    stock:
                      type: integer
                    thumbnail:
                      type: string
                    description:
                      type: string
                  required:
                  - id
                  - name
                  - item_type
                  - price
                  - stock
                  - thumbnail
                  - description
    post:
      summary: Creates an item
      tags:
      - Items
      parameters: []
      responses:
        '201':
          description: item created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                item_type:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
                thumbnail:
                  type: string
                description:
                  type: string
              required:
              - name
              - item_type
              - price
              - stock
              - thumbnail
              - description
  "/items/{id}":
    parameters:
    - name: id
      in: path
      description: ID of the item
      required: true
      schema:
        type: string
    get:
      summary: Retrieves an item
      tags:
      - Items
      responses:
        '200':
          description: item found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  item_type:
                    type: string
                  price:
                    type: number
                  stock:
                    type: integer
                  thumbnail:
                    type: string
                  description:
                    type: string
                required:
                - id
                - name
                - item_type
                - price
                - stock
                - thumbnail
                - description
        '404':
          description: item not found
    put:
      summary: Updates an item
      tags:
      - Items
      parameters: []
      responses:
        '200':
          description: item updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                item_type:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
                thumbnail:
                  type: string
                description:
                  type: string
              required:
              - name
              - item_type
              - price
              - stock
              - thumbnail
              - description
    delete:
      summary: Deletes an item
      tags:
      - Items
      responses:
        '204':
          description: item deleted
        '404':
          description: item not found
